# Path to your oh-my-zsh installation.
# export ZSH=$HOME/.oh-my-zsh

source /usr/share/zsh-antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle git-extras
antigen bundle git-flow-completion
antigen bundle gh
antigen bundle debian
antigen bundle asdf
antigen bundle tmuxinator
antigen bundle node
antigen bundle npm
antigen bundle compleat
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle arzzen/calc.plugin.zsh
antigen bundle git-flow-completion
antigen theme kphoen
antigen apply

DISABLE_AUTO_UPDATE="true"

# User configuration

# github copilot integration

eval "$(gh copilot alias -- zsh)"

# aichat zsh integration
_aichat_zsh() {
    if [[ -n "$BUFFER" ]]; then
        local _old=$BUFFER
        BUFFER+="⌛"
        zle -I && zle redisplay
        BUFFER=$(aichat -e "$_old")
        zle end-of-line
    fi
}
zle -N _aichat_zsh
bindkey '\ee' _aichat_zsh

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

# source $ZSH/oh-my-zsh.sh

setopt INTERACTIVE_COMMENTS
unsetopt correct_all

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi

if [ -f ~/.bash_env ]; then
    . ~/.bash_env
fi

# disable CTRL+s in shell
stty -ixon

export PATH="$PATH:/snap/bin"
export PATH="$PATH:/usr/local/heroku/bin"
export PATH="$PATH:$HOME/local/bin"

if [ -f '/home/deployer/yandex-cloud/path.bash.inc' ]; then source '/home/deployer/yandex-cloud/path.bash.inc'; fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# ASDF
export ASDF_DATA_DIR="/home/deployer/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

# Homebrew
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";

# gpg
export GPG_TTY=$(tty)
